config/routes.rb
Waiveme::Application.routes.draw do
  resources :logins

  resources :approved_appointments

  resources :appointments

  resources :lecturers

  resources :departments

  resources :students

  
  get 'user_login' => "logins#login"  
  get 'department_faculty.json' => "departments#faculty"
  get 'lecturer_details' => "lecturers#details"
  get 'lecturer_details_clid' => "lecturers#details_clid"
  get 'request_appointment' => 'appointments#request_apointment'
  get 'request_appointment_clid' => 'appointments#request_appointment_clid'  
  get 'lecturer_appointments' => "lecturers#appointments"
  get 'modify_appointment' => "lecturers#modify_appointment"
  get 'login_create' => "logins#login_create"
  get '/student_appointment' => "students#appointments"
  
  
  get "welcome/index"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  post "signup" => "users#signup"
  get "profile" => "users#display_profile"
  post "profile_data" => "users#profile_data"
  post "update_profile" => "users#update_profile"
  post "update_profile_data" => "users#update_profile_data"
  get "edit_profile" => "users#edit_profile"
  
  
  resources :users
  resources :sessions

  root 'welcome#index'

end

app/models/approved_appointment.rb
class ApprovedAppointment < ActiveRecord::Base
end

app/controllers/approved_appointments_controller.rb
class ApprovedAppointmentsController < ApplicationController
  before_action :set_approved_appointment, only: [:show, :edit, :update, :destroy]

  # GET /approved_appointments
  # GET /approved_appointments.json
  def index
    @approved_appointments = ApprovedAppointment.all
  end

  # GET /approved_appointments/1
  # GET /approved_appointments/1.json
  def show
  end

  # GET /approved_appointments/new
  def new
    @approved_appointment = ApprovedAppointment.new
  end

  # GET /approved_appointments/1/edit
  def edit
  end

  # POST /approved_appointments
  # POST /approved_appointments.json
  def create
    @approved_appointment = ApprovedAppointment.new(approved_appointment_params)

    respond_to do |format|
      if @approved_appointment.save
        format.html { redirect_to @approved_appointment, notice: 'Approved appointment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @approved_appointment }
      else
        format.html { render action: 'new' }
        format.json { render json: @approved_appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /approved_appointments/1
  # PATCH/PUT /approved_appointments/1.json
  def update
    respond_to do |format|
      if @approved_appointment.update(approved_appointment_params)
        format.html { redirect_to @approved_appointment, notice: 'Approved appointment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @approved_appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /approved_appointments/1
  # DELETE /approved_appointments/1.json
  def destroy
    @approved_appointment.destroy
    respond_to do |format|
      format.html { redirect_to approved_appointments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_approved_appointment
      @approved_appointment = ApprovedAppointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def approved_appointment_params
      params.require(:approved_appointment).permit(:lecturer_id, :student_id, :appointment_time, :appointment_date, :note)
    end
end

app/helpers/approved_appointments_helper.rb
module ApprovedAppointmentsHelper
end

app/views/approved_appointments/_form.html.erb
<%= form_for(@approved_appointment) do |f| %>
  <% if @approved_appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@approved_appointment.errors.count, "error") %> prohibited this approved_appointment from being saved:</h2>

      <ul>
      <% @approved_appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lecturer_id %><br>
    <%= f.number_field :lecturer_id %>
  </div>
  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.number_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :appointment_time %><br>
    <%= f.text_field :appointment_time %>
  </div>
  <div class="field">
    <%= f.label :appointment_date %><br>
    <%= f.text_field :appointment_date %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/approved_appointments/edit.html.erb
<h1>Editing approved_appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @approved_appointment %> |
<%= link_to 'Back', approved_appointments_path %>

app/views/approved_appointments/index.html.erb
<h1>Listing approved_appointments</h1>

<table>
  <thead>
    <tr>
      <th>Lecturer</th>
      <th>Student</th>
      <th>Appointment time</th>
      <th>Appointment date</th>
      <th>Note</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @approved_appointments.each do |approved_appointment| %>
      <tr>
        <td><%= approved_appointment.lecturer_id %></td>
        <td><%= approved_appointment.student_id %></td>
        <td><%= approved_appointment.appointment_time %></td>
        <td><%= approved_appointment.appointment_date %></td>
        <td><%= approved_appointment.note %></td>
        <td><%= link_to 'Show', approved_appointment %></td>
        <td><%= link_to 'Edit', edit_approved_appointment_path(approved_appointment) %></td>
        <td><%= link_to 'Destroy', approved_appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Approved appointment', new_approved_appointment_path %>

app/views/approved_appointments/new.html.erb
<h1>New approved_appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', approved_appointments_path %>

app/views/approved_appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lecturer:</strong>
  <%= @approved_appointment.lecturer_id %>
</p>

<p>
  <strong>Student:</strong>
  <%= @approved_appointment.student_id %>
</p>

<p>
  <strong>Appointment time:</strong>
  <%= @approved_appointment.appointment_time %>
</p>

<p>
  <strong>Appointment date:</strong>
  <%= @approved_appointment.appointment_date %>
</p>

<p>
  <strong>Note:</strong>
  <%= @approved_appointment.note %>
</p>

<%= link_to 'Edit', edit_approved_appointment_path(@approved_appointment) %> |
<%= link_to 'Back', approved_appointments_path %>