config/routes.rb
Waiveme::Application.routes.draw do
  resources :logins

  resources :approved_appointments

  resources :appointments

  resources :lecturers

  resources :departments

  resources :students

  
  get 'user_login' => "logins#login"  
  get 'department_faculty.json' => "departments#faculty"
  get 'lecturer_details' => "lecturers#details"
  get 'lecturer_details_clid' => "lecturers#details_clid"
  get 'request_appointment' => 'appointments#request_apointment'
  get 'request_appointment_clid' => 'appointments#request_appointment_clid'  
  get 'lecturer_appointments' => "lecturers#appointments"
  get 'modify_appointment' => "lecturers#modify_appointment"
  get 'login_create' => "logins#login_create"
  get '/student_appointment' => "students#appointments"
  
  
  get "welcome/index"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  post "signup" => "users#signup"
  get "profile" => "users#display_profile"
  post "profile_data" => "users#profile_data"
  post "update_profile" => "users#update_profile"
  post "update_profile_data" => "users#update_profile_data"
  get "edit_profile" => "users#edit_profile"
  
  
  resources :users
  resources :sessions

  root 'welcome#index'

end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    
    @student = Student.new
    @student.name = params[:student][:name]
    @student.clid = params[:student][:clid]
    @student.email = params[:student][:email]
    @student.password = params[:student][:password]
    
    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render action: 'show', status: :created, location: @student }
      else
        format.html { render action: 'new' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    @student.name = params[:student][:name]
    @student.clid = params[:student][:clid]
    @student.email = params[:student][:email]
    @student.password = params[:student][:password]
    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end

  def appointments
    @student = Student.where(:clid => params[:clid]).first
    @appointments = Appointment.where(:student_id => @student.id)
    render :json => @appointments.to_json
  end
  
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :clid, :email, :password)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :clid %><br>
    <%= f.text_field :clid %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Clid</th>
      <th>Email</th>
      <th>Password</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.clid %></td>
        <td><%= student.email %></td>
        <td><%= student.password %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Clid:</strong>
  <%= @student.clid %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @student.password %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>