config/routes.rb
Waiveme::Application.routes.draw do
  resources :logins

  resources :approved_appointments

  resources :appointments

  resources :lecturers

  resources :departments

  resources :students

  
  get 'user_login' => "logins#login"  
  get 'department_faculty.json' => "departments#faculty"
  get 'lecturer_details' => "lecturers#details"
  get 'lecturer_details_clid' => "lecturers#details_clid"
  get 'request_appointment' => 'appointments#request_apointment'
  get 'request_appointment_clid' => 'appointments#request_appointment_clid'  
  get 'lecturer_appointments' => "lecturers#appointments"
  get 'modify_appointment' => "lecturers#modify_appointment"
  get 'login_create' => "logins#login_create"
  get '/student_appointment' => "students#appointments"
  
  
  get "welcome/index"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  post "signup" => "users#signup"
  get "profile" => "users#display_profile"
  post "profile_data" => "users#profile_data"
  post "update_profile" => "users#update_profile"
  post "update_profile_data" => "users#update_profile_data"
  get "edit_profile" => "users#edit_profile"
  
  
  resources :users
  resources :sessions

  root 'welcome#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
end

app/models/approved_appointment.rb
class ApprovedAppointment < ActiveRecord::Base
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/friend.rb
class Friend < ActiveRecord::Base
end

app/models/lecturer.rb
class Lecturer < ActiveRecord::Base
end

app/models/login.rb
class Login < ActiveRecord::Base
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def new_connection
    
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :set_login, only: [:show, :edit, :update, :destroy]

  # GET /logins
  # GET /logins.json
  def index
    @logins = Login.all
  end

  # GET /logins/1
  # GET /logins/1.json
  def show
  end

  # GET /logins/new
  def new
    @login = Login.new
  end

  # GET /logins/1/edit
  def edit
  end

  def login
    @l = Login.where(:clid => params[:clid]).first
    status = {}
    @role = Student.where(:clid => params[:clid]).first
    
    if(@role.nil?)
      @role = Lecturer.where(:clid => params[:clid]).first
    end  
    
    if(@l.password == params[:password])
      status["success"] = true
      status["role"] = @role.class.name
    else
      status["success"] = false
    end  
    render :json => status.to_json
  end
  
    
    def login_create
      @l = Login.new
      @l.clid= params[:clid]
      @l.password = params[:password]
      @l.save
      render :json => @l.to_json
    end
  
  # POST /logins
  # POST /logins.json
  def create
    @login = Login.new
    @login.clid = params[:login][:clid]
    @login.password = params[:login][:password]
    respond_to do |format|
      if @login.save
        format.html { redirect_to @login, notice: 'Login was successfully created.' }
        format.json { render action: 'show', status: :created, location: @login }
      else
        format.html { render action: 'new' }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logins/1
  # PATCH/PUT /logins/1.json
  def update
    @login.clid = params[:login][:clid]
    @login.password = params[:login][:password]
    respond_to do |format|
      if @login.save
        format.html { redirect_to @login, notice: 'Login was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1
  # DELETE /logins/1.json
  def destroy
    @login.destroy
    respond_to do |format|
      format.html { redirect_to logins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      @login = Login.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_params
      params.require(:login).permit(:clid, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def signup 
    @user = User.new
    @user.email = params[:email]
    @user.password = params[:password]
    @user.password_confirmation = params[:password_confirmation]
    resp_hash = {}    
    respond_to do |format|
      if @user.save
        format.html { redirect_to root_url, notice: "Signed up!" }
        resp_hash[:status] = "Created"
        resp_hash[:message] = "User SignedUP Successfully"
        format.json { render :json => resp_hash.to_json }
      else
        format.html { render action: 'new' }
        resp_hash[:status] = "Failed"
        resp_hash[:message] = "User Signup has been failed."
        format.json { render :json => resp_hash.to_json }
      end
    end
  end
  
  def create
    @user = User.new(params[:user])
    resp_hash = {}    
    respond_to do |format|
      if @user.save
        format.html { redirect_to root_url, notice: "Signed up!" }
        resp_hash[:status] = "Created"
        resp_hash[:message] = "User SignedUP Successfully"
        format.json { render :json => resp_hash.to_json }
      else
        format.html { render action: 'new' }
        resp_hash[:status] = "Failed"
        resp_hash[:message] = "User Signup has been failed."
        format.json { render :json => resp_hash.to_json }
      end
    end
  end
  
  def display_profile
    @user = User.find(session[:user_id])    
  end
  
  def profile_data
    @user = User.find_by_email(params[:email])
      resp_hash = {}
      respond_to do |format|              
        resp_hash[:status] = "Success"
        resp_hash[:data] = @user
        format.json { render :json => resp_hash.to_json }
     end
  end
  
  def update_profile
    @user = User.find(session[:user_id])
    @user.first_name = params[:user][:first_name]
    @user.last_name = params[:user][:last_name]
    @user.Adress = params[:user][:Adress]
    @user.City = params[:user][:City]
    @user.State = params[:user][:State]
    @user.zip_code = params[:user][:zip_code]
    @user.phone = params[:user][:phone]
    @user.save
    redirect_to :action => "display_profile"
  end
  
  def update_profile_data
    @user = User.find_by_email(params[:email])
    resp_hash = {}
    @user.first_name = params[:firstName]
    @user.last_name = params[:lastName]
    @user.Adress = params[:address]
    @user.City = params[:city]
    @user.State = params[:state]
    @user.zip_code = params[:zip_code]
    @user.phone = params[:phone]
    @user.save
    
    respond_to do |format|              
      resp_hash[:status] = "Success"
      resp_hash[:data] = @user
      format.json { render :json => resp_hash.to_json }
    end
  end
  
  def edit_profile
    @user = User.find(session[:user_id])
  end  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/lecturers_helper.rb
module LecturersHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/logins/_form.html.erb
<%= form_for(@login) do |f| %>
  <% if @login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
      <% @login.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :clid %><br>
    <%= f.text_field :clid %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logins/edit.html.erb
<h1>Editing login</h1>

<%= render 'form' %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>

app/views/logins/index.html.erb
<h1>Listing logins</h1>

<table>
  <thead>
    <tr>
      <th>Clid</th>
      <th>Password</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @logins.each do |login| %>
      <tr>
        <td><%= login.clid %></td>
        <td><%= login.password %></td>
        <td><%= link_to 'Show', login %></td>
        <td><%= link_to 'Edit', edit_login_path(login) %></td>
        <td><%= link_to 'Destroy', login, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Login', new_login_path %>

app/views/logins/new.html.erb
<h1>New login</h1>

<%= render 'form' %>

<%= link_to 'Back', logins_path %>

app/views/logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Clid:</strong>
  <%= @login.clid %>
</p>

<p>
  <strong>Password:</strong>
  <%= @login.password %>
</p>

<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>

app/views/users/display_profile.html.erb
<style type="text/css">
html body div #menu, html body div #menu a {background-color: transparent; font-family: Georgia; color: #212e36;}

body {background-color: #d8f0f4; background-image: url(http://i.imgur.com/bFQ6V.png);}

#container {width: 500px; margin: 25px;}

#two, #three, #four {background-color: #fff; padding: 8px; font-family: tahoma; color: #212e36; font-size: 11px;}
#two, #three {width: 250px; text-align: center;}
#four {text-align: justify;}

a {color: #3f7464;}

.head {font-family: Georgia; color: #192e28; font-size: 20px; text-align: center;}
#one .head {font-size: 50px;}

b {color: #50193E;}
</style>

<div style="width:50%;margin-left:25%;">
<tr>
<td id="two">
<div class="head">Profile</div>
  <span>First Name :  <%= @user.first_name %></span><br/>
  <span>Last Name :   <%= @user.last_name %></span><br/>
<span>Email: <%=@user.email %> </span><br/>
<span></span><br>
</td>
<td id="three">
<div class=""><u><b>Details</b></u></div>
  <span>Address :  <%= @user.Adress %></span><br/>
   <span>City :  <%= @user.City %></span><br/>
  <span>State :  <%= @user.State %></span><br/>
  <span>ZIP Code :  <%= @user.zip_code %></span><br/>
  <span>Phone :  <%= @user.phone %></span><br/>
</td>
</tr>
 
  
<div class="head"> <b><a href="/edit_profile" > Edit Profile</a></b></div>
</div>

app/views/users/edit_profile.html.erb
<div style="margin:5% 0 0 25%;">
  <%=form_for @user,:url => update_profile_path, method: :post do |f|%>
<table><tr>
  <td>
First Name: 
    </td><td><%= f.text_field :first_name%>
</td>
</tr>
<br/>
<tr>
  <td>
Last Name: 
    </td><td><%= f.text_field :last_name%>
</td>
</tr>
<tr>
  <td>
Email: 
  </td><td><%= @user.email%>
</td>
</tr>
<tr>  
  <td><br/>
Details : <br/>
    </td>
</tr>
<tr>
  <td>
Address: 
  </td><td><%= f.text_field :Adress%>
</td>
</tr>
<tr>
  <td>
City: 
  </td><td><%= f.text_field :City%>
</td>
</tr>
  
<tr>
  <td>
State: 
  </td><td><%= f.text_field :State%>
</td>
</tr>

<tr>
  <td>
Zip Code: 
  </td><td><%= f.text_field :zip_code%>
</td>
</tr>  
<tr>
  <td>
Phone: 
  </td><td><%= f.text_field :phone%>
</td>
</tr>
  
</table>
  <%=f.submit "Update Profile"%>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>