config/routes.rb
Waiveme::Application.routes.draw do
  resources :logins

  resources :approved_appointments

  resources :appointments

  resources :lecturers

  resources :departments

  resources :students

  
  get 'user_login' => "logins#login"  
  get 'department_faculty.json' => "departments#faculty"
  get 'lecturer_details' => "lecturers#details"
  get 'lecturer_details_clid' => "lecturers#details_clid"
  get 'request_appointment' => 'appointments#request_apointment'
  get 'request_appointment_clid' => 'appointments#request_appointment_clid'  
  get 'lecturer_appointments' => "lecturers#appointments"
  get 'modify_appointment' => "lecturers#modify_appointment"
  get 'login_create' => "logins#login_create"
  get '/student_appointment' => "students#appointments"
  
  
  get "welcome/index"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  post "signup" => "users#signup"
  get "profile" => "users#display_profile"
  post "profile_data" => "users#profile_data"
  post "update_profile" => "users#update_profile"
  post "update_profile_data" => "users#update_profile_data"
  get "edit_profile" => "users#edit_profile"
  
  
  resources :users
  resources :sessions

  root 'welcome#index'

end

app/models/lecturer.rb
class Lecturer < ActiveRecord::Base
end

app/controllers/lecturers_controller.rb
class LecturersController < ApplicationController
  before_action :set_lecturer, only: [:show, :edit, :update, :destroy]

  # GET /lecturers
  # GET /lecturers.json
  def index
    @lecturers = Lecturer.all
  end

  # GET /lecturers/1
  # GET /lecturers/1.json
  def show
  end

  # GET /lecturers/new
  def new
    @lecturer = Lecturer.new
    @departments = Department.all
  end

  # GET /lecturers/1/edit
  def edit
    @departments = Department.all
  end

  # POST /lecturers
  # POST /lecturers.json
  def create
    @lecturer = Lecturer.new
    @lecturer.name = params[:lecturer][:name]
    @lecturer.department_id = params[:lecturer][:department_id]
    @lecturer.status = params[:lecturer][:status]
    @lecturer.available_hrs = params[:lecturer][:available_hrs]
    @lecturer.clid = params[:lecturer][:clid]
    
    respond_to do |format|
      if @lecturer.save
        format.html { redirect_to @lecturer, notice: 'Lecturer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lecturer }
      else
        format.html { render action: 'new' }
        format.json { render json: @lecturer.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def details
    @l = Lecturer.find(params[:lecturer_id])
    render :json => @l.to_json    
  end
  
  def details_clid
    @l = Lecturer.where(:clid =>params[:clid]).first
    if !@l.nil?
      render :json => @l.to_json  
    else
      render :text => "there is no lecturer with this clid"
    end
  end
  
  def appointments
    @l = Lecturer.where(:clid => params[:clid]).first
    @aps = Appointment.where(:lecturer_id => @l.id)
    render :json => @aps.to_json
  end
  
  def modify_appointment
    @ap = Appointment.find(params[:appointment_id])
    @ap.note += params[:note].to_s
    if(!params[:approved].blank?)
      @ap.approved = params[:approved]    
    end
    @ap.save
    render :json => @ap.to_json
  end
  
  # PATCH/PUT /lecturers/1
  # PATCH/PUT /lecturers/1.json
  def update
    @lecturer.name = params[:lecturer][:name]
    @lecturer.department_id = params[:lecturer][:department_id]
    @lecturer.status = params[:lecturer][:status]
    @lecturer.available_hrs = params[:lecturer][:available_hrs]
    @lecturer.clid = params[:lecturer][:clid]
    respond_to do |format|
      if @lecturer.save
        format.html { redirect_to @lecturer, notice: 'Lecturer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lecturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lecturers/1
  # DELETE /lecturers/1.json
  def destroy
    @lecturer.destroy
    respond_to do |format|
      format.html { redirect_to lecturers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lecturer
      @lecturer = Lecturer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lecturer_params
      params.require(:lecturer).permit(:name, :department_id, :available_hrs, :status)
    end
end

app/helpers/lecturers_helper.rb
module LecturersHelper
end

app/views/lecturers/_form.html.erb
<%= form_for(@lecturer) do |f| %>
  <% if @lecturer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lecturer.errors.count, "error") %> prohibited this lecturer from being saved:</h2>

      <ul>
      <% @lecturer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :clid %><br>
    <%= f.text_field :clid %>
  </div>
  <div class="field">
    <%= f.label :department_id %><br>
    <%=f.select 'department_id', options_from_collection_for_select(@departments, 'id', 'name')%>
    <%#= f.number_field :department_id %>
  </div>
  <div class="field">
    <%= f.label :available_hrs %><br>
    <%= f.text_field :available_hrs %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_area :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lecturers/edit.html.erb
<h1>Editing lecturer</h1>

<%= render 'form' %>

<%= link_to 'Show', @lecturer %> |
<%= link_to 'Back', lecturers_path %>

app/views/lecturers/index.html.erb
<h1>Listing lecturers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Department</th>
      <th>Available hrs</th>
      <th>CLID</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @lecturers.each do |lecturer| %>
      <tr>
        <td><%= lecturer.name %></td>
        <td><%= lecturer.department_id %></td>
        <td><%= lecturer.available_hrs %></td>
        <td><%= lecturer.clid %></td>
        <td><%= lecturer.status %></td>
        <td><%= link_to 'Show', lecturer %></td>
        <td><%= link_to 'Edit', edit_lecturer_path(lecturer) %></td>
        <td><%= link_to 'Destroy', lecturer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lecturer', new_lecturer_path %>

app/views/lecturers/new.html.erb
<h1>New lecturer</h1>

<%= render 'form' %>

<%= link_to 'Back', lecturers_path %>

app/views/lecturers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lecturer.name %>
</p>

<p>
  <strong>Department:</strong>
  <%= @lecturer.department_id %>
</p>

<p>
  <strong>Available hrs:</strong>
  <%= @lecturer.available_hrs %>
</p>

<p>
  <strong>Status:</strong>
  <%= @lecturer.status %>
</p>

<%= link_to 'Edit', edit_lecturer_path(@lecturer) %> |
<%= link_to 'Back', lecturers_path %>